Repository SSUMC-7th/Android_A, pull requests merged in 2024-10, with the labels that each got.

#10 [totoro/#3] 1주차 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/study/umc_7th/BottomNavigationBar.kt
  app/src/main/java/umc/study/umc_7th/Content.kt
  app/src/main/java/umc/study/umc_7th/ContentCollectionView.kt
  app/src/main/java/umc/study/umc_7th/Footer.kt
  app/src/main/java/umc/study/umc_7th/HomeFragment.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/MainBanner.kt
  app/src/main/java/umc/study/umc_7th/PromotionBanner.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
Labels: 1주차

#9 Ike/#3
  .idea/deploymentTargetSelector.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/migrations.xml
  .idea/other.xml
  app/build.gradle.kts
  app/src/main/java/umc/study/umc_7th/BottomNavigationBar.kt
  app/src/main/java/umc/study/umc_7th/Content.kt
  app/src/main/java/umc/study/umc_7th/ContentCollectionView.kt
  app/src/main/java/umc/study/umc_7th/Footer.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/MainBanner.kt
  app/src/main/java/umc/study/umc_7th/MiniPlayer.kt
  app/src/main/java/umc/study/umc_7th/PromotionBanner.kt
  app/src/main/res/drawable/ic_bottom_home.xml
  app/src/main/res/drawable/ic_bottom_home_no_select.png
  app/src/main/res/drawable/ic_bottom_home_select.png
  app/src/main/res/drawable/ic_bottom_locker_no_select.png
  app/src/main/res/drawable/ic_bottom_locker_select.png
  app/src/main/res/drawable/ic_bottom_look_no_select.png
  app/src/main/res/drawable/ic_bottom_look_select.png
  app/src/main/res/drawable/ic_bottom_search_no_select.png
  app/src/main/res/drawable/ic_bottom_search_select.png
  gradle/libs.versions.toml
Labels: 1주차

#12 [totoro/#4] 2주차 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/study/umc_7th/BottomNavigationBar.kt
  app/src/main/java/umc/study/umc_7th/Content.kt
  app/src/main/java/umc/study/umc_7th/ImageLoader.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumDetailsPage.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumFrame.kt
  app/src/main/java/umc/study/umc_7th/album/IncludedContentsPage.kt
  app/src/main/java/umc/study/umc_7th/album/TabLayout.kt
  app/src/main/java/umc/study/umc_7th/album/TopButtonBar.kt
  app/src/main/java/umc/study/umc_7th/album/VideosPage.kt
  app/src/main/java/umc/study/umc_7th/home/ContentCollectionView.kt
  app/src/main/java/umc/study/umc_7th/home/Footer.kt
  app/src/main/java/umc/study/umc_7th/home/HomeFragment.kt
  app/src/main/java/umc/study/umc_7th/home/MainBanner.kt
  app/src/main/java/umc/study/umc_7th/home/PromotionBanner.kt
  app/src/main/java/umc/study/umc_7th/song/ContentFrame.kt
  app/src/main/java/umc/study/umc_7th/song/FooterActionBar.kt
  app/src/main/java/umc/study/umc_7th/song/LyricsView.kt
  app/src/main/java/umc/study/umc_7th/song/PlayProgressControlPanel.kt
  app/src/main/java/umc/study/umc_7th/song/SongActivity.kt
  app/src/main/java/umc/study/umc_7th/song/TopButtonBar.kt
  app/src/main/java/umc/study/umc_7th/ui/theme/Theme.kt
  app/src/main/res/layout/fragment_album.xml
Labels: 2주차

#13 [Ike/#4] 2주차 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/study/umc_7th/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/MiniPlayer.kt
  app/src/main/java/umc/study/umc_7th/SongActivity.kt
  app/src/main/java/umc/study/umc_7th/SongContent.kt
  app/src/main/java/umc/study/umc_7th/TabLayout_Album.kt
Labels: 2주차

#14 [Ike/#8] 3주차 구현
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/study/umc_7th/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/BottomNavigationBar.kt
  app/src/main/java/umc/study/umc_7th/LockerFragment.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/MainBanner.kt
  app/src/main/java/umc/study/umc_7th/MiniPlayer.kt
  app/src/main/java/umc/study/umc_7th/SongContent.kt
  gradle/libs.versions.toml
Labels: 3주차

#22 [Ike/#16] 4주차 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/Timer/Timer.kt
  app/src/main/java/Timer/ui/theme/Color.kt
  app/src/main/java/Timer/ui/theme/Theme.kt
  app/src/main/java/Timer/ui/theme/Type.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/SongContent.kt
  app/src/main/res/values/strings.xml
Labels: 4주차

#23 [Ean/#16] 4주차 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/java/timer/MainActivity.kt
  app/src/main/java/timer/Timer.kt
  app/src/main/java/timer/TimerDisplay.kt
  app/src/main/java/umc/study/umc_7th/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/AlbumFragmentTop.kt
  app/src/main/java/umc/study/umc_7th/AlbumMusicList.kt
  app/src/main/java/umc/study/umc_7th/ContentFrame.kt
  app/src/main/java/umc/study/umc_7th/Lyric.kt
  app/src/main/java/umc/study/umc_7th/MiniPlayer.kt
  app/src/main/java/umc/study/umc_7th/Navigation.kt
  app/src/main/java/umc/study/umc_7th/PlayProgressBar.kt
  app/src/main/java/umc/study/umc_7th/SnsSharebar.kt
  app/src/main/java/umc/study/umc_7th/SongActivity.kt
  app/src/main/java/umc/study/umc_7th/SongTopButton.kt
  app/src/main/java/umc/study/umc_7th/TabLayout.kt
  app/src/main/java/umc/study/umc_7th/ViewModel.kt
Labels: 4주차

#28 [Ike/#25] 5주차 미션 구현
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/src/main/java/umc/study/umc_7th/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/LockerFragment.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/MiniPlayer.kt
  app/src/main/java/umc/study/umc_7th/MusicViewModel.kt
  app/src/main/java/umc/study/umc_7th/SongActivity.kt
  app/src/main/java/umc/study/umc_7th/SongContent.kt
  memo/.gitignore
  memo/build.gradle.kts
  memo/proguard-rules.pro
  memo/src/androidTest/java/com/example/memo/ExampleInstrumentedTest.kt
  memo/src/main/AndroidManifest.xml
  memo/src/main/java/com/example/memo/MemoActivity.kt
  memo/src/main/java/com/example/memo/ui/theme/Color.kt
  memo/src/main/java/com/example/memo/ui/theme/Theme.kt
  memo/src/main/java/com/example/memo/ui/theme/Type.kt
  memo/src/main/res/drawable/ic_launcher_background.xml
  memo/src/main/res/drawable/ic_launcher_foreground.xml
  memo/src/main/res/mipmap-anydpi/ic_launcher.xml
  memo/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  memo/src/main/res/mipmap-hdpi/ic_launcher.webp
  memo/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  memo/src/main/res/mipmap-mdpi/ic_launcher.webp
  memo/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  memo/src/main/res/mipmap-xhdpi/ic_launcher.webp
  memo/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  memo/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  memo/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  memo/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  memo/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  memo/src/main/res/values/colors.xml
  memo/src/main/res/values/strings.xml
  memo/src/main/res/values/themes.xml
  memo/src/test/java/com/example/memo/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 5주차

#27 [Ean/#25] 5주차 구현
  .idea/other.xml
  app/src/main/java/Memo/DisplayActivity.kt
  app/src/main/java/Memo/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/MiniPlayer.kt
  app/src/main/java/umc/study/umc_7th/PlayProgressBar.kt
  app/src/main/java/umc/study/umc_7th/ViewModel.kt
  settings.gradle.kts
Labels: 5주차
