Repository SSUMC-7th/Android_A, pull requests merged in 2024-11, with the labels that each got.

#31 [Ike/#30] 6주차 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/java/umc/study/umc_7th/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/ContentCollectionView.kt
  app/src/main/java/umc/study/umc_7th/LockerFragment.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/MiniPlayer.kt
  app/src/main/java/umc/study/umc_7th/MusicViewModel.kt
Labels: 6주차

#33 [Ean/#30] 6주차 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/study/umc_7th/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/Content.kt
  app/src/main/java/umc/study/umc_7th/ContentFrame.kt
  app/src/main/java/umc/study/umc_7th/ForegroundService.kt
  app/src/main/java/umc/study/umc_7th/MiniPlayer.kt
  app/src/main/java/umc/study/umc_7th/Navigation.kt
  app/src/main/java/umc/study/umc_7th/TabLayout.kt
  app/src/main/java/umc/study/umc_7th/ViewModel.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumFragmentTop.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumItem.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumMusicList.kt
  app/src/main/java/umc/study/umc_7th/locker/LockerFragment.kt
  app/src/main/java/umc/study/umc_7th/locker/LockerMusic.kt
  app/src/main/java/umc/study/umc_7th/main/home/BottomNavigationBar.kt
  app/src/main/java/umc/study/umc_7th/main/home/HorizontalCollection.kt
  app/src/main/java/umc/study/umc_7th/main/home/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/main/home/MainBanner.kt
  app/src/main/java/umc/study/umc_7th/main/home/Promotion.kt
  app/src/main/java/umc/study/umc_7th/main/home/SnsSharebar.kt
  app/src/main/java/umc/study/umc_7th/main/song/ContentFrame.kt
  app/src/main/java/umc/study/umc_7th/main/song/Lyric.kt
  app/src/main/java/umc/study/umc_7th/main/song/MiniPlayer.kt
  app/src/main/java/umc/study/umc_7th/main/song/PlayProgressBar.kt
  app/src/main/java/umc/study/umc_7th/main/song/SongActivity.kt
  app/src/main/java/umc/study/umc_7th/main/song/SongTopButton.kt
Labels: 6주차

#34 [Hoony#30] 6주차 구현
  .idea/deploymentTargetSelector.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/other.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/study/umc_7th/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/Bottom_navi_Bar.kt
  app/src/main/java/umc/study/umc_7th/Content.kt
  app/src/main/java/umc/study/umc_7th/ContentCollectionView.kt
  app/src/main/java/umc/study/umc_7th/Footer.kt
  app/src/main/java/umc/study/umc_7th/HomeFragment.kt
  app/src/main/java/umc/study/umc_7th/LockerFragment.kt
  app/src/main/java/umc/study/umc_7th/LookFragment.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/MainBanner.kt
  app/src/main/java/umc/study/umc_7th/PromotionBanner.kt
  app/src/main/java/umc/study/umc_7th/SearchFragment.kt
  app/src/main/java/umc/study/umc_7th/Song.kt
  app/src/main/java/umc/study/umc_7th/SongActivity.kt
  app/src/main/java/umc/study/umc_7th/SongContent.kt
  app/src/main/java/umc/study/umc_7th/SongViewModel.kt
  app/src/main/java/umc/study/umc_7th/StopWatchActivity.kt
  app/src/main/java/umc/study/umc_7th/TopButtonBar.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_song.xml
  app/src/main/res/layout/fragment_album.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_locker.xml
  app/src/main/res/layout/fragment_look.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/menu/bottom_navi.xml
Labels: 6주차

#38 [Ean/#37] 7주차 구현
  .idea/other.xml
  app/src/main/java/umc/study/umc_7th/TabLayout.kt
  app/src/main/java/umc/study/umc_7th/ViewModel.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumFragmentTop.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumItem.kt
  app/src/main/java/umc/study/umc_7th/album/AlbumMusicList.kt
  app/src/main/java/umc/study/umc_7th/content/AlbumDao.kt
  app/src/main/java/umc/study/umc_7th/content/AlbumRepository.kt
  app/src/main/java/umc/study/umc_7th/content/AppDataBase.kt
  app/src/main/java/umc/study/umc_7th/content/Content.kt
  app/src/main/java/umc/study/umc_7th/content/ContentDao.kt
  app/src/main/java/umc/study/umc_7th/content/ContentRepository.kt
  app/src/main/java/umc/study/umc_7th/locker/LockerFragment.kt
  app/src/main/java/umc/study/umc_7th/locker/LockerMusic.kt
  app/src/main/java/umc/study/umc_7th/main/home/BottomNavigationBar.kt
  app/src/main/java/umc/study/umc_7th/main/home/HorizontalCollection.kt
  app/src/main/java/umc/study/umc_7th/main/home/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/main/home/MainBanner.kt
  app/src/main/java/umc/study/umc_7th/main/song/ContentFrame.kt
  app/src/main/java/umc/study/umc_7th/main/song/MiniPlayer.kt
  app/src/main/java/umc/study/umc_7th/main/song/PlayProgressBar.kt
  app/src/main/java/umc/study/umc_7th/main/song/SongActivity.kt
Labels: 7주차

#46 [Ike/#43] 8주차 구현
  .idea/deploymentTargetSelector.xml
  .idea/other.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/study/umc_7th/LoginActivity.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/SignUpActivity.kt
  app/src/main/java/umc/study/umc_7th/SongActivity.kt
  app/src/main/java/umc/study/umc_7th/data/source/local/AlbumDB.kt
  app/src/main/java/umc/study/umc_7th/ui/composables/Login.kt
  app/src/main/java/umc/study/umc_7th/ui/composables/SignUp.kt
  app/src/main/java/umc/study/umc_7th/ui/screen/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/ui/screen/LockerFragment.kt
  app/src/main/java/umc/study/umc_7th/ui/screen/LookFragment.kt
  app/src/main/java/umc/study/umc_7th/ui/viewmodel/LoginViewModel.kt
  app/src/main/java/umc/study/umc_7th/ui/viewmodel/MockMusicViewModel.kt
  app/src/main/java/umc/study/umc_7th/ui/viewmodel/MusicViewModel.kt
  app/src/main/java/umc/study/umc_7th/ui/viewmodel/SignUpViewModel.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 8주차

#48 [Ean/#43] 8주차 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/study/umc_7th/AroundFragment.kt
  app/src/main/java/umc/study/umc_7th/ViewModel.kt
  app/src/main/java/umc/study/umc_7th/content/AlbumDao.kt
  app/src/main/java/umc/study/umc_7th/content/AppDataBase.kt
  app/src/main/java/umc/study/umc_7th/locker/LockerAlbum.kt
  app/src/main/java/umc/study/umc_7th/locker/LockerFragment.kt
  app/src/main/java/umc/study/umc_7th/locker/LockerMusic.kt
  app/src/main/java/umc/study/umc_7th/main/home/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/user/LoginActivity.kt
  app/src/main/java/umc/study/umc_7th/user/SignUpActivity.kt
  app/src/main/java/umc/study/umc_7th/user/UserDao.kt
  app/src/main/java/umc/study/umc_7th/user/UserRepository.kt
  app/src/main/java/umc/study/umc_7th/user/UserViewModel.kt
Labels: 8주차

#53 [Ike/#51] 9주차 구현
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/study/umc_7th/LoginActivity.kt
  app/src/main/java/umc/study/umc_7th/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/SignUpActivity.kt
  app/src/main/java/umc/study/umc_7th/data/model/ApiResponse.kt
  app/src/main/java/umc/study/umc_7th/data/source/remote/ApiService.kt
  app/src/main/java/umc/study/umc_7th/data/source/remote/NetworkManager.kt
  app/src/main/java/umc/study/umc_7th/data/source/remote/Service.kt
  app/src/main/java/umc/study/umc_7th/ui/composables/Login.kt
  app/src/main/java/umc/study/umc_7th/ui/composables/NetworkViewInterface.kt
  app/src/main/java/umc/study/umc_7th/ui/composables/SignUp.kt
  app/src/main/java/umc/study/umc_7th/ui/viewmodel/LoginViewModel.kt
  app/src/main/java/umc/study/umc_7th/ui/viewmodel/SignUpViewModel.kt
  app/src/main/java/umc/study/umc_7th/utils/SharedPreferencesHelper.kt
  app/src/main/res/xml/network_security_config.xml
Labels: :sparkles: Chapter 9

#55 [Ean/#51] 9주차 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/study/umc_7th/user/AuthNetworkInterface.kt
  app/src/main/java/umc/study/umc_7th/user/AuthPayload.kt
  app/src/main/java/umc/study/umc_7th/user/LoginActivity.kt
  app/src/main/java/umc/study/umc_7th/user/SignUpActivity.kt
  app/src/main/java/umc/study/umc_7th/user/UserViewModel.kt
  app/src/main/res/xml/network_security_config.xml
Labels: :sparkles: Chapter 9

#54 [totoro/#51] 9주차 구현
  .gitignore
  app/src/main/java/umc/study/umc_7th/DateSerializer.kt
  app/src/main/java/umc/study/umc_7th/FloApplication.kt
  app/src/main/java/umc/study/umc_7th/data/ContentRepository.kt
  app/src/main/java/umc/study/umc_7th/data/local/LocalDatabase.kt
  app/src/main/java/umc/study/umc_7th/data/local/dao/LikedContentDao.kt
  app/src/main/java/umc/study/umc_7th/data/local/entity/LikedContentEntity.kt
  app/src/main/java/umc/study/umc_7th/data/network/Responses.kt
  app/src/main/java/umc/study/umc_7th/data/network/Server.kt
  app/src/main/java/umc/study/umc_7th/data/network/ServerEndpoint.kt
  app/src/main/java/umc/study/umc_7th/di/viewmodel/MainViewModelModule.kt
  app/src/main/java/umc/study/umc_7th/service/ContentPlayerService.kt
  app/src/main/java/umc/study/umc_7th/service/ServiceHandler.kt
  app/src/main/java/umc/study/umc_7th/ui/login/LoginActivity.kt
  app/src/main/java/umc/study/umc_7th/ui/main/BottomNavigationBar.kt
  app/src/main/java/umc/study/umc_7th/ui/main/MainActivity.kt
  app/src/main/java/umc/study/umc_7th/ui/main/MainViewModel.kt
  app/src/main/java/umc/study/umc_7th/ui/main/album/AlbumFragment.kt
  app/src/main/java/umc/study/umc_7th/ui/main/album/IncludedMusicsPage.kt
  app/src/main/java/umc/study/umc_7th/ui/main/album/TopButtonBar.kt
  app/src/main/java/umc/study/umc_7th/ui/main/browsing/BrowsingFragment.kt
  app/src/main/java/umc/study/umc_7th/ui/main/browsing/MusicChartPage.kt
  app/src/main/java/umc/study/umc_7th/ui/main/browsing/TabLayout.kt
  app/src/main/java/umc/study/umc_7th/ui/main/browsing/TitleBar.kt
  app/src/main/java/umc/study/umc_7th/ui/main/home/HomeFragment.kt
  app/src/main/java/umc/study/umc_7th/ui/main/locker/LockerFragment.kt
  app/src/main/java/umc/study/umc_7th/ui/main/locker/SavedAlbumsPage.kt
  app/src/main/java/umc/study/umc_7th/ui/main/locker/TabLayout.kt
  app/src/main/java/umc/study/umc_7th/ui/signup/SignUpActivity.kt
  app/src/main/java/umc/study/umc_7th/ui/signup/SignUpViewModel.kt
  app/src/main/java/umc/study/umc_7th/ui/song/SongActivity.kt
  app/src/main/java/umc/study/umc_7th/ui/song/SongViewModel.kt
  app/src/main/res/layout/fragment_browsing.xml
  gradle/libs.versions.toml
  mock/build.gradle.kts
  mock/src/main/java/com/example/mock/Converters.kt
  mock/src/main/java/com/example/mock/DateSerializer.kt
  mock/src/main/java/com/example/mock/MockServer.kt
  mock/src/main/java/com/example/mock/MockStream.kt
  mock/src/main/java/com/example/mock/Responses.kt
Labels: :sparkles: Chapter 9
